#!/usr/bin/env python3
"""
merge_portraits.py

Composites each champion's face PNG with its star-rank border (top + bottom
caps) into one final portrait PNG. This is a one-time/whenever-roster-changes
build step -- the website just loads the finished PNGs, no client-side
layering needed.

INPUT (edit data/champions_source.json to match your real roster):
  data/champions_source.json
    { "champions": [
        {"id": "champ_001", "name": "...", "class": "Cosmic", "star": 7,
         "face": "raw/faces/champ_001.png"},
        ...
    ]}

  raw/borders/<star>star_top.png     e.g. 7star_top.png, 6star_top.png
  raw/borders/<star>star_bottom.png
  (falls back to 7star_top/bottom.png if a specific star rank is missing)

OUTPUT:
  images/champions/<id>.png          <- final composited portrait
  data/champions.json                <- final list the website actually reads
                                         (id, name, class, star, image)

Usage:
  python3 scripts/merge_portraits.py
"""
import json
from pathlib import Path
from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
SOURCE_JSON = ROOT / "data" / "champions_source.json"
BORDERS_DIR = ROOT / "raw" / "borders"
OUT_DIR = ROOT / "images" / "champions"
FINAL_JSON = ROOT / "data" / "champions.json"
FINAL_JS = ROOT / "data" / "champions.js"

OUT_DIR.mkdir(parents=True, exist_ok=True)

_border_cache = {}


def get_border(star: int, part: str) -> Image.Image | None:
    """part is 'top' or 'bottom'. Falls back to 7star if the specific
    star-rank border doesn't exist yet."""
    key = (star, part)
    if key in _border_cache:
        return _border_cache[key]

    candidates = [
        BORDERS_DIR / f"{star}star_{part}.png",
        BORDERS_DIR / f"7star_{part}.png",
    ]
    for c in candidates:
        if c.exists():
            img = Image.open(c).convert("RGBA")
            _border_cache[key] = img
            return img

    _border_cache[key] = None
    return None


def merge_one(champ: dict) -> str:
    face_path = ROOT / champ["face"]
    face = Image.open(face_path).convert("RGBA")

    top = get_border(champ.get("star", 7), "top")
    bottom = get_border(champ.get("star", 7), "bottom")

    canvas = Image.new("RGBA", face.size, (0, 0, 0, 0))
    canvas.alpha_composite(face)
    if top is not None:
        top_resized = top.resize(face.size) if top.size != face.size else top
        canvas.alpha_composite(top_resized)
    if bottom is not None:
        bottom_resized = bottom.resize(face.size) if bottom.size != face.size else bottom
        canvas.alpha_composite(bottom_resized)

    out_path = OUT_DIR / f"{champ['id']}.png"
    canvas.save(out_path)
    return f"images/champions/{champ['id']}.png"


def main():
    if not SOURCE_JSON.exists():
        raise SystemExit(
            f"Missing {SOURCE_JSON}. Run scripts/generate_sample_data.py for a "
            f"demo roster, or create this file yourself for your real roster."
        )

    source = json.loads(SOURCE_JSON.read_text())
    final_list = []

    for champ in source["champions"]:
        face_path = ROOT / champ["face"]
        if not face_path.exists():
            print(f"SKIP {champ['id']} ({champ['name']}): face file not found at {face_path}")
            continue
        image_path = merge_one(champ)
        final_list.append({
            "id": champ["id"],
            "name": champ["name"],
            "class": champ["class"],
            "star": champ.get("star", 7),
            "image": image_path,
        })

    payload = {"champions": final_list}
    FINAL_JSON.write_text(json.dumps(payload, indent=2))

    # Also write a plain-JS version so the site can run via file:// (double
    # click, no server) without hitting fetch()'s local-file CORS block.
    js_content = (
        "// Auto-generated by scripts/merge_portraits.py -- do not edit by hand.\n"
        "window.CHAMPIONS_DATA = " + json.dumps(payload, indent=2) + ";\n"
    )
    FINAL_JS.write_text(js_content)

    print(f"Merged {len(final_list)} portraits -> {OUT_DIR}/")
    print(f"Wrote final roster -> {FINAL_JSON}")
    print(f"Wrote inline data -> {FINAL_JS}")


if __name__ == "__main__":
    main()